
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    
</head>
<body>

  <div class="grid-x grid-margin-x">
    <div class="large-12 medium-12 small-12 columns" >
      <img src=<?php echo App::config("url") ?>img\pocetna.png width= 100% >
      <p></p> 
    </div>
  </div>

  <section class="wedo py-5" id="services" >
		<div class="container py-lg-5" >
			<div class="w3l_head1" style="padding: 0 0 0">
				<h4 class="heading text-center"> Uzgoj i dostava rezanog cvijeća.</h3>
				<p class="subs1 mt-4 text-center mx-auto">Lokalno uzgojeno cvijeće direktno sa polja! Duži život u vazi! Manja cijena!</p>
      </div>
      <div class="row about-info-grids text-center py-lg-5 py-3 mt-3">
							<div class="col-md-4 about-info about-info1">
                <!-- <span class="fa fa-tint"></span> -->
                <img src=<?php echo App::config("url") ?>img\lijeva.png width = 40%>
								<h4></h4>
								<p></p>
							</div>
							<div class="col-md-4 about-info about-info2">
                <!-- <span class="fa fa-leaf"></span> -->
                <img src=<?php echo App::config("url") ?>img\srednja.png width = 40%>
								<h4></h4>
								<p></p>
							</div>
							<div class="col-md-4 about-info about-info3">
                <!-- <span class="fa fa-pagelines"></span> -->
                <img src=<?php echo App::config("url") ?>img\desna.png width = 40%>
								<h4></h4>
								<p></p>
							</div>
					</div>
   </div>
  </section>

  

<!-- <div class="grid-container">
  <div class="grid-x grid-margin-x" ;>
    <div class="cell small-4" >
      <img src=<?php echo App::config("url") ?>img\lijeva.png width = 60%>
      <P></P>
    </div>
    <div class="cell small-4" >
    <img src=<?php echo App::config("url") ?>img\srednja.png width = 60%>
    <p></p>
    
  </div>
  <div class="cell small-4" >
    <img src=<?php echo App::config("url") ?>img\desna.png width = 60%>
    <p></p>
    
  </div>
   
  </div>
</div> -->

</body>
</html> 
