<form class="log-in-form" method="post" 
                    action="<?php echo App::config("url") ?>narudzba/email/">

                    <input type="text" name="b1" value="<?php echo $_POST["b1"]?>" ><br />
                        <h3>Naručeno <?php echo $_POST["b2"]?> kom </h3><br />
                        <h3>Naručeno <?php echo $_POST["b3"]?> kom </h3><br />
                        <h3>Naručeno <?php echo $_POST["b5"]?> kom </h3><br />
                        <input class="button expanded" type="submit" value="Odustani" /> 
                    </form>