<section class="foot-1 py-5" id="contact">
		<div class="container py-lg-5">
			<div class="row foot-1-top">
				<div class="col-lg-3 col-md-6 col-sm-6 foot-1_grid_left">
					<h4 class="mb-3">KONTAKT</h4>
					<div class="foot-top pt-3">
						<ul>
							<li><h4>Obiteljsko poljoprivredno gospodarstvo Alošinac</h4></li>
							<li><p>Adresa: Braće Radić 11, Bistrinci, 31551 Belišće</p></li>
							<li><p>Telefon: 031/662 228</p><br /><p> Mobitel: 091/566 7552</p></li>
							<li><p>E-mail: alosinac111@gmail.com</p></li>
						</ul>
					</div>
				</div>
				
				<div class="col-lg-6 foot-1_grid_right">
					<h4 class="mb-4">Pošaljite nam poruku!</h4>
					<div class="contact_grid_right mt-5 mx-auto text-left">
						<form method="post" action="<?php echo App::config("url") ?>testsetting.php">

							<div class="row contact_top">
								<div class="col-sm-6">
									<input type="text" name="name" placeholder="Vaše Ime" value="<?php echo $name; ?>" required="">
								</div>
								<div class="col-sm-6">
									<input type="email" name="email" placeholder="Vaš E-mail" value="<?php echo $email; ?>" required="">
								</div>
							</div>							
								<textarea name="message" value="<?php echo $message; ?>" onblur="if (this.value == '') 
								{this.value = 'Message...';}" required="">Vaša poruka...</textarea>
								<input type="submit" value="Pošalji">
								
						</form>
			</div>
				</div>
			</div>
			
		</div>
</section>





