<section class="blog_w3l py-5" id="news" >
	<div class="container py-lg-5" style="padding: 5% 5% 0">
<!-- <h4 class="heading text-left">Ostalo rezano cvijeće</h4> -->
				<p class="subs mt-4 text-left mx-auto"  >
                <?php echo "Dobrodošli" . " " . Session::getInstance()->getUser()->firstname . "!"; ?>
                Ovdje možete izvršiti svoju narudžbu...</p>
			</div>

            <div>
				<div  class="col-lg-12">
                    <div style="padding:0% 0% 0% 0%" class="row blog_w3l_left1">
                        <div class="col">
                            <h3></h3>
                        </div>
                        <div class="col">
                            <h3>PROIZVOD</h3>
                        </div>
                        <div class="col">
                            <h3>1+</h3><h4>(kn)</h4>
                        </div>
                        <div class="col">
                            <h3>20+</h3><h4>(kn)</h4>
                        </div>
                        <div class="col">
                            <h3>100+</h3><h4>(kn)</h4>
                        </div>
                        <div class="col">
                            <h3>Naručiti</h3><h4>(broj komada)</h4>
                        </div>
                    </div>
			    </div>	
		    </div>

            <form action="<?php echo App::config("url") ?>narudzba/izracun" method="POST">
            
            <div>
				<div  class="col-lg-12 ">
				    <div style="padding:0% 0% 0% 0%" class="row blog_w3l_left1">
                        <div class="col">
                         <img src="<?php echo App::config("url")?>img\CoralC.jpg" 
                          style="width:50%" alt="news image" class="img-fluid">   
                        </div>
                        <div class="col">
                            <h3>Coral Charm</h3>
                        </div>
                        <div class="col">
                            <h3>6.00</h3>
                        </div>
                        <div class="col">
                            <h3>5.00</h3>
                        </div>
                        <div class="col">
                            <h3>4.00</h3>
                        </div>
                        <div class="col">
                            <label>
                                <input type="number" step="1" name="b1"
                                value="<?php echo $_SESSION["b1"]; ?>" selected="selected" >
                            </label>
                        </div>
                        <br />
                    </div>
                </div>
            </div>
            <div>
				<div class="col-lg-12 blog_w3l_left">
				    <div style="padding:0% 0% 0% 0%" class="row blog_w3l_left1">
                        <div class="col">
                         <img src="<?php echo App::config("url")?>img\KarlR.jpg" 
                         style="width:50%" alt="news image" class="img-fluid">   
                        </div>
                        <div class="col">
                            <h3>Karl Rosenfield</h3>
                        </div>
                        <div class="col">
                            <h3>6.00</h3>
                        </div>
                        <div class="col">
                            <h3>5.00</h3>
                        </div>
                        <div class="col">
                            <h3>4.00</h3>
                        </div>
                        <div class="col">
                            <label>
                                <input type="number" step="1" name="b2"
                                value="<?php echo $_SESSION["b2"]; ?>"  >
                            </label>
                        </div>
                        <br />
                    </div>
                </div>
            </div>
            <div>
				<div class="col-lg-12 blog_w3l_left">
				    <div style="padding:0% 0% 0% 0%" class="row blog_w3l_left1">
                        <div class="col">
                         <img src="<?php echo App::config("url")?>img\SarahBB.jpg" 
                         style="width:50%" alt="news image" class="img-fluid">   
                        </div>
                        <div class="col">
                            <h3>Sarah Bernhardt</h3>
                        </div>
                        <div class="col">
                            <h3>6.00</h3>
                        </div>
                        <div class="col">
                            <h3>5.00</h3>
                        </div>
                        <div class="col">
                            <h3>4.00</h3>
                        </div>
                        <div class="col">
                            <label>
                                <input type="number" step="1" name="b3"
                                value="<?php echo $_SESSION["b3"]; ?>"  >
                            </label>
                        </div>
                        <br />
                    </div>
                </div>
            </div>
            <div>
				<div class="col-lg-12 blog_w3l_left">
				    <div style="padding:0% 0% 0% 0%" class="row blog_w3l_left1">
                        <div class="col">
                         <img src="<?php echo App::config("url")?>img\DuchesseN.jpg"
                         style="width:50%" alt="news image" class="img-fluid">   
                        </div>
                        <div class="col">
                            <h3>Duchesse De Nemours</h3>
                        </div>
                        <div class="col">
                            <h3>6.00</h3>
                        </div>
                        <div class="col">
                            <h3>5.00</h3>
                        </div>
                        <div class="col">
                            <h3>4.00</h3>
                        </div>
                        <div class="col">
                            <label>
                                <input type="number" step="1" name="b4"
                                value="<?php echo $_SESSION["b4"]; ?>"  >
                            </label>
                        </div>
                        <br />
                    </div>
                </div>
            </div>
            <div>
				<div class="col-lg-12 blog_w3l_left">
				    <div style="padding:0% 0% 0% 0%" class="row blog_w3l_left1">
                        <div class="col">
                         <img src="<?php echo App::config("url")?>img\Ranunculus.jpg" 
                         style="width:50%" alt="news image" class="img-fluid">   
                        </div>
                        <div class="col">
                            <h3>Ranunculus</h3>
                        </div>
                        <div class="col">
                            <h3>6.00</h3>
                        </div>
                        <div class="col">
                            <h3>5.00</h3>
                        </div>
                        <div class="col">
                            <h3>4.00</h3>
                        </div>
                        <div class="col">
                            <label>
                                <input type="number" step="1" name="b5"
                                value="<?php echo $_SESSION["b5"]; ?>"  >
                            </label>
                        </div>
                        <br />
                    </div>
                </div>
            </div>


                    <div class="col">
                                <input class="button expanded" type="submit" value="Dodaj u košaricu" /> 
                                <button type="submit"><a href="<?php echo App::config("url") ?>index" >Odustani</a></button>
                                <button type="submit"><a href="<?php unset($_SESSION['b1']);
                                                                     unset($_SESSION['b2']);
                                                                     unset($_SESSION['b3']);
                                                                     unset($_SESSION['b4']);
                                                                     unset($_SESSION['b5']); ?>" >Isprazni košaricu</a></button>            
                    </div>
                    
    </div>	
                   
                    </form>
                    
                
    </div>

</section>

<?php

?>



		