
<section class="blog_w3l py-5" id="news">
	<div class="container py-lg-5">
				<!-- <h4 class="heading text-left">Ostalo rezano cvijeće</h4> -->
				<p class="subs mt-4 text-left mx-auto">
                <?php echo "Dobrodošli" . " " . Session::getInstance()->getUser()->firstname . "!"; ?>
                Trenutno u ponudi...</p>
			</div>

            <div class="row blog_w3l_top py-lg-5 py-3 mt-3 ">
				<div class="col-lg-12 blog_w3l_left">
                    <div class="row blog_w3l_left1">
                    
                        <div class="col">
                            <h3>PROIZVOD</h3>
                        </div>
                        <div class="col">
                            <h3>Kom</h3>
                        </div>
                        <div class="col">
                            <h3>1+</h3>
                        </div>
                        <div class="col">
                            <h3>20+</h3>
                        </div>
                        <div class="col">
                            <h3>100+</h3>
                        </div>
                        <div class="col">
                            <h3>Naručeno</h3>
                        </div>
                        <div class="col">
                            <h3>CIJENA</h3>
                        </div>
            
                    </div>
			    </div>	
		    </div>




		<div class="row blog_w3l_top py-lg-5 py-3 mt-3 ">
				<div class="col-lg-12 blog_w3l_left">
                <?php foreach($narudzba as $narudzba): ?>
				<div class="row blog_w3l_left1">
               
                        <div class="col">
                         <img src="<?php echo App::config("url")?>img\<?php echo $narudzba->productimage?>" alt="news image" class="img-fluid">
                            
                        </div>
                        <div class="col">
                            <h3><?php echo $narudzba->productname?></h3>
                        </div>
                        <div class="col">
                            <h3>1+</h3>
                        </div>
                        <div class="col">
                            <h3>20+</h3>
                        </div>
                        <div class="col">
                            <h3>100+</h3>
                        </div>
                        <div class="col">
                        <label>
                            <input type="number" step="1" name="stock"
                            value="<?php echo Request::post("stock") ?>" />
                        </label>
                        </div>
                        <div class="col">
                        rezultat
                        </div>
                        <br />
					<!-- <div class="col-md-5 blog_w3l-1">
						<img src="images/g4.jpg" alt="news image" class="img-fluid">
					</div>
					<div class="col-md-7 blog_w3l-2">
						<h3><?php echo $narudzba->productname?></h3>
						<p class="mt-3"><?php echo $narudzba->productdescription?></p>
					</div> -->
                    
                    
				</div>
                <?php endforeach; ?>
			</div>	
		</div>

	</div>
</section>
 
