o nama
<section class="news py-5" id="about">
		<div class="container py-lg-5">
			<div class="w3l_head">
				<h3 class="heading text-center">About Us</h3>
				<p class="subs mt-4 text-center mx-auto">Integer porttitor mollisar lorem, at molestie arcu pulvinar ut</p>
			</div>		
				<div class="row news-grids py-lg-5 py-3 mt-3 text-center">
						<div class="col-md-4 newsgrid1">
							<img src="images/g1.jpg" alt="news image" class="img-fluid">
							<div class="news_btm mt-4">
								<h6>Etiam eu ante risus</h6>
								<p>Praesent semper </p>
							</div>
						</div>
						<div class="col-md-4 mt-md-0 mt-5 newsgrid2">
							<img src="images/g2.jpg" alt="news image" class="img-fluid">
							<div class="news_btm mt-4">
								<h6>Etiam eu ante risus</h6>
								<p>Praesent semper </p>
							</div>
						</div>
						<div class="col-md-4  mt-md-0 mt-5 newsgrid3">
							<img src="images/g3.jpg" alt="news image" class="img-fluid">
							<div class="news_btm mt-4">
								<h6>Etiam eu ante risus</h6>
								<p>Praesent semper </p>
							</div>
						</div>
				</div>
			<p class="text-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore.Nulla pellentesque mi non laoreet eleifend. Integer porttitor mollisar lorem, at molestie arcu pulvinar ut. Proin ac fermentum est.</p>
		</div>
	</section>