<section class="blog_w3l py-5" id="news">
	<div class="container py-lg-5">
			<div class="w3l_head" style="padding: 7% 0 0">
				<h4 class="heading text-center">Ostalo rezano cvijeće</h4>
				<p class="subs mt-4 text-center mx-auto">Trenutno u ponudi...Za narudžbu izvršite prijavu ili registraciju!</p>
				<p class="subs mt-4 text-center mx-auto">... ili nas kontaktirajte na tel: 091/566 7552, email: alosinac111@gmail.com</p>
			</div>

		<div class="row blog_w3l_top py-lg-5 py-3 mt-3 ">
		<?php foreach($ostalo as $ostalo):
			if($ostalo->category==2){
			?>
				<div class="col-lg-6 blog_w3l_left">
				<div class="row blog_w3l_left1">
					<div class="col-md-5 blog_w3l-1">
					<img src="<?php echo App::config("url")?>img\<?php echo $ostalo->productimage?>" alt="news image" width="10" height="100" class="img-fluid">
					</div>
					<div class="col-md-7 blog_w3l-2">
						<h3><?php echo $ostalo->productname?></h3>
						<p class="mt-3"><?php echo $ostalo->productdescription?></p>
					</div>
				</div>
			</div>	
			<?php }?>
			<?php endforeach; ?>
		</div>

	</div>
</section>