<div class="login-page">
  <div class="form">
        
    <form class="login-form" method="post"
      action="<?php echo App::config("url") ?>admin/login">
        	  <input type="email" name="email" placeholder="alosinac111@gmail.com"
              value="alosinac111@gmail.com">
            <input type="password" name="password" placeholder="oioi"
              value="oioi">
          <button type="submit">login</button>
          <?php echo $poruka ?>
              <p class="message">Ukoliko još niste registrirani, učinite to 
                  <a href="<?php echo App::config("url") ?>register/signup">ovdje!</a>
              </p> 
       
    
  </div>
</div>

<!-- <script>
$('.message a').click(function(){
   $('form').animate({height: "toggle", opacity: "toggle"}, "slow");
});
</script> -->