<form class="log-in-form" method="post" 
action="<?php echo App::config("url") ?>register/registerlogin">

 <?php include_once "kontrole.phtml" ?>
 <div class="form">
 <div class="grid-x">
    <div class="large-6 columns" style="padding: 10px;">
    <button type="submit"><a href="<?php echo App::config("url") ?>index" >Odustani</a></button>
    </div>
    <div class="large-6 columns"  style="padding: 10px;">
        <input type="submit" class="button expanded" value="Dodaj novog" />
    </div>
 </div>
 </div>
 

</form>
<?php echo $poruka ?>