<form class="log-in-form" method="post" 
action="<?php echo App::config("url") ?>register/registerlogin">

 <?php include_once "kontrole.phtml" ?>
   <div class="form">
      <div>
         <div class="large-6 columns" style="padding: 2px;">
            <button type="submit">Dodaj</a></button>
         </div>
         <div class="large-6 columns" style="padding: 2px;">
            <button type="submit"><a href="<?php echo App::config("url") ?>index" >Odustani</a></button>
         </div>
      </div>
   <?php echo $poruka ?>
   </div>
 

</form>
